/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.io.File;
import java.io.IOException;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.apache.avro.file.DataFileReader;
import org.apache.avro.generic.GenericArray;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.GenericDatumReader;
import org.apache.avro.generic.GenericRecord;
import org.apache.avro.io.DatumReader;

/**
 *
 * @author evan yang
 */
public class numOfFile {

    public static void main(String[] args) throws IOException {
        String msgSchemaContent = "{ \n"
                + "    \"protocol\":\"wb\",\n"
                + " \n"
                + "    \"types\":[\n"
                + "    {\n"
                + "        \"type\": \"record\",\n"
                + "        \"name\": \"wb\",\n"
                + "        \"fields\": [\n"
                + "\n"
                + "        {\n"
                + "            \"name\": \"id\",  \n"
                + "            \"type\":\"string\"\n"
                + "        },\n"
                + "         \n"
                + "        {\n"
                + "            \"name\": \"user_id\", \n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "\n"
                + "        {\n"
                + "            \"name\": \"rootuser_id\",\n"
                + "            \"type\":\"string\"\n"
                + "        },\n"
                + "\n"
                + "        {\n"
                + "            \"name\": \"mid\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "\n"
                + "        {\n"
                + "            \"name\": \"rootid\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "\n"
                + "        {\n"
                + "            \"name\": \"rel_time\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "\n"
                + "        {\n"
                + "            \"name\": \"input_time\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "\n"
                + "        {\n"
                + "            \"name\": \"send_ip\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"send_srcport\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"province_name\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"city_name\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"isp_name\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"net_type\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"client_type\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"mobile_type\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"message_type\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"audit_status\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"user_fansnum\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"user_friendsnum\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"mid_commentnum\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"mid_retweetnum\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "\n"
                + "        {\n"
                + "            \"name\": \"rootid_commentnum\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"rootid_retweetnum\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"client_remark\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"m_text\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"is_long\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        \n"
                + "        {\n"
                + "            \"name\": \"pic_url\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"pic_content\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"audio_url\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "\n"
                + "        {\n"
                + "            \"name\": \"audio_content\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"video_url\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"video_content\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"sp_type\",\n"
                + "            \"type\": \"string\"\n"
                + "        }\n"
                + "      ]\n"
                + "    },\n"
                + "    \n"
                + "    {\n"
                + "        \"type\": \"record\",\n"
                + "        \"name\": \"docs\",\n"
                + "        \"fields\": [\n"
                + "        {\n"
                + "            \"name\": \"doc_schema_name\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"sign\",\n"
                + "            \"type\": \"string\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"doc_set\",\n"
                + "            \"type\": {\n"
                + "                \"type\":\"array\",\n"
                + "                \"items\":\"bytes\"\n"
                + "            }\n"
                + "        }\n"
                + "        ]\n"
                + "    }\n"
                + "    ]\n"
                + "}\n"
                + "";
        Protocol protocol = Protocol.parse(msgSchemaContent);
        Schema msgschema = protocol.getType("docs");
        File f = new File("E:\\wb_mqtest.uv");
        DatumReader<GenericRecord> reader = new GenericDatumReader<GenericRecord>(msgschema);
        DataFileReader<GenericRecord> dataFileReader = null;

        dataFileReader = new DataFileReader<GenericRecord>(f, reader);
        int count = 0;
        while (dataFileReader.hasNext()) {
            GenericRecord dxr = dataFileReader.next();
            GenericArray docsSet = (GenericData.Array<GenericRecord>) dxr.get("doc_set");
            count++;
            System.out.println("size : " + docsSet.size() + " count : " + count);
        }
        dataFileReader.close();
    }
}
